Modele/urls.py
from django.urls import path
from . import views


app_name = 'Modele'


urlpatterns = [
	# post views
	path('<int:pk>/', views.ModeleDetail.as_view(), name='detail'),
	path('', views.ModeleListView.as_view(), name='list'),
	path('add/', views.ModeleCreateView.as_view(), name='add'),
	path('update/<int:pk>/', views.ModeleUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/', views.ModeleDeleteView.as_view(), name="delete")
]

Tricycle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
from django.conf.urls.i18n import i18n_patterns

from Tricycleapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.TricycleView.as_view(), name='index'),
    path('Tricycle',include('Tricycleapp.urls')),
    path('Tricycleauth/',include('Tricycleauth.urls')),
    path('Modele/', include('Modele.urls', namespace='Modele')),
    path('reservation/', views.ReservationView.as_view(), name='reservation'),
]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', views.TricycleView.as_view(), name='index'),
    path('Tricycle/',include('Tricycleapp.urls',namespace='tricycle')),
    path('Tricycleauth/',include('Tricycleauth.urls',namespace='tricycleauth')), 
    path('Modele/', include('Modele.urls', namespace='modele')),
    path('reservation/', views.ReservationView.as_view(), name='reservation'),
)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



'''
On utilise souvent un nom pour les apps quand on écrit plusieurs applications
et dont les noms des urls spnt les memes. Alors les app_namme permettent de se
rediriger vers cet url selin de nom de l'app defini
'''

Tricycleapp/urls.py
from django.urls import path
from Tricycleapp import views


app_name = 'Tricycleapp'

urlpatterns = [
    path('<int:pk>/', views.TricycleDetail.as_view(), name='detail'),
	path('list/', views.TricycleList.as_view(), name='list'),
	path('add/', views.TricycleAdd.as_view(), name='add'),
	path('update/<int:pk>/', views.TricycleUpdate.as_view(), name='update'),
	path('delete/<int:pk>/', views.TricycleDelete.as_view(), name="delete"),
	path('<int:pk>/achat/', views.TricycleAchat.as_view(), name='payement'),
	path('reservation/', views.ReservationView.as_view(), name='reservation'),
	path('confirmation/', views.payement_view, name='confirmation'),
	path('contact/',views.contact,name='contact')
  
]

templates/Tricycle/add.html
{% extends 'base.html' %}

{% block title %}Tricycle ajouter{% endblock %}

{% block content %}
<div class="mt-3 mx-3">
	<h1 class="text-center fs-3 fw-bolder">Ajouter un Tricycle</h1>
	<hr class="offset-md-4 offset-3 border-2 text-primary col-6 col-md-4  rounded-pill" style="height: 3px;">
	<div class="offset-md-2">
		<form method="post" class="offset-md-1 row col-md-8 col-sm-6 col px-3 shadow pt-3 mx-2 mx-md-5" enctype="multipart/form-data">
			{% csrf_token %}
			{% for field in form %}
			<div class="mb-3">
				<label class="form-label">{{ field.label }}</label>
				{{ field }}
			</div>
			{% endfor %}
			<input type="submit" class="btn btn-primary col-6 col-md-8 offset-md-2 offset-3 mb-3" value="Ajouter Voiture">
		</form>
	</div>
</div>
{% endblock content %}

templates/Tricycle/confirmation.html
{% extends 'base.html' %} {% block title %}Tricycle Liste{% endblock %}{% load static %} 
{% block style %}
<style>
  .message {
    border-radius: 15% 85% 15% 85% / 100% 0% 100% 0% ;
  }
</style>
{% endblock style %}

{% block content %}
<br><br><br><br><br> <br>
<p></p>
<div class="container">

    <div class="row mx-4">
  
      <div class="col-lg-9 mx-auto">
  
        <div class="message">
  
          <h4 class="text-center mx-auto">
            <strong>Paiement effectué, Merci!!!</strong>
          </h4>
  
        </div>
  
        
  
      </div>
  
    </div>
  
  </div>
  

{% endblock content %}

templates/Tricycle/contact.html
{% extends 'base.html' %} {% block title %}Tricycle Liste{% endblock %}{% load static %} 
{% block style %}
<style>
  .message {
    border-radius: 15% 85% 15% 85% / 100% 0% 100% 0% ;
  }
</style>
{% endblock style %}

{% block content %}
<br><br><br><br><br> <br>
<p></p>
<div class="container">

    <div class="row mx-4">
  
      <div class="col-lg-9 mx-auto">
  
        <div class="message">
  
          <h4 class="text-center mx-auto">
            Nous avons bien reçu votre message, nos équipes vous contacterons d'ici peu.<br>
            En attendant vous pouvez louer des tricycles!!!
          </h4>
  
        </div>
  
        
  
      </div>
  
    </div>
  
  </div>
  

{% endblock content %}

templates/Tricycle/detail.html
{% extends 'base.html' %}

{% block title %}Tricycle Detail{% endblock %}
{% block style %}
<style>
  .btn {
        font-family: "Raleway", sans-serif;
        font-weight: 500;
        font-size: 16px;
        letter-spacing: 1px;
        display: inline-block;
        padding: 10px 30px;
        border-radius: 50px;
        transition: 0.5s;
        color: #3498db;
        border: 2px solid #3498db;
  }
    .btn:hover{
        background-color: black;
        color: white;
    }
    .btn i.bi-cart-check-fill { 
        color: #3498db !important; 
    }
    
    .image-container {
        position: relative;
    }

    .hovered::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        opacity: 1;
        transition: opacity 0.3s ease;
    }

    .portfolio-info {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        opacity: 0;
        transition: opacity 0.3s ease;
    }

    .hovered .portfolio-info {
        opacity: 1;
    }
    .price {
        font-size: 18px;
        width: 150px;
        font-weight: bold;
        
        
    }
    .pushed-right {
        margin-left: 10px;
    }

</style>
{% endblock style %}

{% load static %}
{% block content %}
<br><br><br><br><br><br><br><br><br>
<div class="row mx-3">
    
    <div class="row-cols-1 offset-md-1 card shadow-custom border-0 col-md-9 mx-auto">
        <div class="row justify-content-center">
            <div class="col-12 col-md-4 portfolio-item filter-app">
                <div class="portfolio-wrap">
                    <div class="image-container">
                        <img src="{% static 'assets/img/'|add:tricycle.image.url %}" class="img-fluid" alt="">
                        <div class="portfolio-info">
                            <div class="portfolio-links">
                                <a href="{% static 'assets/img/'|add:tricycle.image.url %}" data-gallery="portfolioGallery" class="portfolio-lightbox" title="{{tricycle.name}}">
                                    <i class="bx bx-plus"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row-cols-1 col-md-6 col-xxl-4 col-lg-5 col-xl-5">
                <div class="top">
                    <h2 class="mt-4 font-weight-bold text-grey"> {{ tricycle.name }} {{ tricycle.marque }} </h2>
                    <div>
                        <span class="font-weight-bold text-grey">  <strong>Poids:</strong> {{ tricycle.weight }}</span> 
                    </div>
                    
                </div>
                <div class="mt-3 form-text">Découvrez une nouvelle façon de vous déplacer en louant notre tricycle confortable et pratique. Réservez dès maintenant et profitez d'une expérience de conduite unique !</div>
                <hr>
                <div class="mb-4">
                    <form class="rounded-pill shadow">
                        <div class="row align-items-center">
                            <div class="col">
                                <span class="input-group add-to-cart shadow-custom">
                                    <div class="input-group-prepend">
                                        <h6 class="price pushed-right" data-aos="fade-up">  {{ tricycle.price }} FCFA/H</h6>
                                    </div>
                                </span>
                            </div>
                            <div class="col-auto">
                                <a href="" class="text-decoration-none" id="cart-button">
                                    <button class="btn" data-toggle="tooltip" data-placement="top" title="Reserver un essai">
                                        <i class="bi bi-cart-check-fill text-light"></i>
                                    </button>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            
        </div>
    </div>
    
</div>

{% endblock content %}

{% block script%}
<script>

    document.getElementById('cart-button').addEventListener('click', function(e) {
        e.preventDefault();
        var tricyclePk = "{{ tricycle.pk }}";
        var url = "{% url 'Tricycleapp:payement' pk=tricycle.pk %}".replace('tricycle.pk', tricyclePk);
        window.location.href = url;
    });

    const imageContainer = document.querySelector('.image-container');

    imageContainer.addEventListener('mouseover', function() {
        this.classList.add('hovered');
    });

    imageContainer.addEventListener('mouseout', function() {
        this.classList.remove('hovered');
    });
</script>
{% endblock script %}

templates/Tricycle/error.html
{% extends 'base.html' %}

{% block title %}Voiture Modifier{% endblock %}

{% block content %}
<br><br><br><br><br><br><br><br><br><br> <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <div class="container mt-5">
        <div class="row mb-4">
            <div class="col-md-4">
                <form method="post">
                    {% csrf_token %}

                    <!-- Afficher les erreurs du formulaire -->
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>Erreur lors de la soumission du formulaire :</strong>
                            <ul>
                                {% for error in form.non_field_errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}

                    <!-- Afficher les erreurs de chaque champ -->
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.errors %}
                                <ul class="alert alert-danger">
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Réserver</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/Tricycle/index.html
{% extends 'base.html' %} 
{% load static %}

{% block style %}
<style>
  .btn {
  font-family: "Raleway", sans-serif;
  font-weight: 500;
  font-size: 16px;
  letter-spacing: 1px;
  display: inline-block;
  padding: 10px 30px;
  border-radius: 50px;
  transition: 0.5s;
  color: #3498db;
  border: 2px solid #3498db;
  }
  .btn:hover{
    background-color: black;
    color: white;
  }
  .carousel {
    
    width: 100%;
    height: 100%;
    border-radius: 15px;
  }
  h6{
    font-weight: bold;
  }
</style>
{% endblock style %}

{% block content %}


  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">

    <div class="container">
      <div class="row">
        <div class="col-lg-6 pt-5 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center">
          <h1 data-aos="fade-up">Louer des tricycles</h1>
          <h2 data-aos="fade-up" data-aos-delay="400">Nous mettons à votre dispositions des cycles à trois roues pour vos activités</h2>
          <div data-aos="fade-up" data-aos-delay="800">
            <a href="#portfolio" class="btn-get-started scrollto">Réserver</a>
          </div>
        </div>
        <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="fade-left" data-aos-delay="200">
          
          <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img class="carousel" src="{% static 'assets/img/space/carousel-1.jpeg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                  <h6> <strong>Vivez une expérience unique.</strong> </h6>
                  
                </div>
              </div>
              <div class="carousel-item">
                <img class="carousel" src="{% static 'assets/img/space/carousel-2.jpeg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                  <h6><strong>Offrez-vous une bouffée d'air frais.</strong> </h6>
                </div>
              </div>
              <div class="carousel-item">
                <img class="carousel" src="{% static 'assets/img/space/carousel-3.jpeg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                  <h6> <strong>Laissez-vous porter au rythme de la ville.</strong> </h6>
                </div>
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
          
        </div>
        

        </div>
      </div>
    </div>

  </section><!-- End Hero -->

  <main id="main">



    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
      <div class="container">

        <div class="row">
          <div class="col-md-6 col-lg-6 d-flex align-items-stretch mb-5 mb-lg-0">
            <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
              <div class="icon"><i class="bx bx-smile"></i></i></div>
              <h4 class="title"><a href="">Facilité d'utilisation</a></h4>
              <p class="description">Réservez votre tricycle en quelques clics grâce à notre plateforme conviviale et intuitive.</p>
            </div>
          </div>
        
          <div class="col-md-6 col-lg-6 d-flex align-items-stretch mb-5 mb-lg-0">
            <div class="icon-box" data-aos="fade-up" data-aos-delay="200">
              <div class="icon"><i class="bx bx-check-shield"></i></div>
              <h4 class="title"><a href="">Fiabilité et disponibilité</a></h4>
              <p class="description">Notre plateforme de réservation de tricycle garantit une disponibilité 24/7 et une fiabilité sans faille pour des trajets en toute tranquillité.</p>
            </div>
          </div>
        </div>

      </div>
    </section><!-- End Services Section -->

    

    
    <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
      <div class="container">

        <div class="section-title" data-aos="fade-up">
          <h2>Nos tricycles</h2>
          <p>Quoi de plus bon que le confort!</p>
        </div>


        <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="400">
          {% for tricycle in tricycles %}
            <div class="col-lg-4 col-md-4 portfolio-item filter-app">
              <div class="portfolio-wrap">
                <img src="{% static 'assets/img/'|add:tricycle.image.url %}" class="img-fluid" alt="">
                <div class="portfolio-info">
                  <div class="portfolio-links">
                    <a href="{% static 'assets/img/'|add:tricycle.image.url %}" data-gallery="portfolioGallery" class="portfolio-lightbox" title="{{tricycle.name}}"><i class="bx bx-plus"></i></a>
                    <a href="{% url 'Tricycleapp:detail' tricycle.pk %}" title="Détails"><i class="bx bx-link"></i></a>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      
        <div class="offset-5 col-md-3 mt-2">
          <a href=" {% url 'Tricycleapp:list' %} " class="btn"> tous les tricycles</a>
        </div>

      </div>
    </section><!-- End Portfolio Section -->


    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container">

        <div class="section-title" data-aos="fade-up">
          <h2>Contactez Nous</h2>
        </div>

        <div class="row">

          <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
            <div class="contact-about">
              <h3>Kloboto</h3>
              <p>Plateforme de réservation de tricycle.</p>
              <div class="social-links">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 mt-4 mt-md-0" data-aos="fade-up" data-aos-delay="200">
            <div class="info">
              <div>
                <i class="ri-map-pin-line"></i>
                <p>C 158, 4ème Maison après la Pharmacie Ciné Concorde 09BP 285 Cotonou Bénin</p>
              </div>

              <div>
                <i class="ri-mail-send-line"></i>
                <p>info@tricycle.com</p>
              </div>

              <div>
                <i class="ri-phone-line"></i>
                <p>+229 62 26 77 77</p>
              </div>

            </div>
          </div>

          <div class="col-lg-5 col-md-12" data-aos="fade-up" data-aos-delay="300">
            <form action="{% url 'Tricycleapp:contact'%}" method="post" class="form-group" > {% csrf_token %}

              <div class="form-group">
                <label for="name"></label>
                <input 
                  type="text" 
                  name="name"
                  class="form-control"
                  id="name"
                  placeholder="Votre Nom"
                  required
                >
              </div>
            
              <div class="form-group">  
                <label for="email"></label>
                <input
                  type="email" 
                  name="email"
                  class="form-control" 
                  id="email"
                  placeholder="Votre Email"
                  required
                >
              </div>
            
              <div class="form-group">
                <label for="subject"></label>
                <input
                  type="text"
                  name="subject"
                  class="form-control"
                  id="subject"
                  placeholder="Objet"
                  required
                >
              </div>
            
              <div class="form-group">
                <label for="message"></label>
                <textarea
                  name="message"
                  class="form-control" 
                  id="message"
                  rows="5"
                  placeholder="Message"
                  required
                ></textarea>
              </div>
              <br>
              <div class="text-center">
                <button class="btn" type="submit">Envoyer</button>
              </div>
            
            </form>
            
          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->
    

  </main><!-- End #main -->

{% endblock content %}

 

templates/Tricycle/list.html
{% extends 'base.html' %} {% block title %}Tricycle Liste{% endblock %}{% load static %} 
{% block style %}
<style>
  .btn {
  font-family: "Raleway", sans-serif;
  font-weight: 500;
  font-size: 16px;
  letter-spacing: 1px;
  display: inline-block;
  padding: 10px 30px;
  border-radius: 50px;
  transition: 0.5s;
  color: #3498db;
  border: 2px solid #3498db;
  }
  .btn:hover{
      background-color: black;
      color: white;
  }
</style>
{% endblock style %}

{% block content %}
<br><br><br><br><br> <br>
<p></p>
<div class="">
    <div class="row mx-4">
        <div class="row col-lg-9 mx-auto">
            <div class="row fs-3 fw-bolder">
                <h1 class="text-center mx-auto" data-aos="fade-up mt-6">Choisissez votre perle rare chez nous</h1>
            </div>
            <hr>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-4 justify-content-end">
                {% for tricycle in tricycles %}
                <div class="mb-3 col d-flex">
                    <div class="card h-100 px-2 w-100">
                        <div class="position-relative h-50">
                            <img src="{% static 'assets/img/'|add:tricycle.image.url %}" class="card-img-top h-100 w-100" alt="...">
                        </div>
                        <div class="card-body d-flex flex-column">
                            <div class="mt-auto mx-auto">
                                <h5 class="card-title">{{ tricycle.name }}</h5>
                                <a href="{% url 'Tricycleapp:detail' tricycle.pk %}" class="btn">Plus <i class="bi bi-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/Tricycle/success.html
{% extends 'base.html' %}

{% block style %}
<style>
  .btn {
  font-family: "Raleway", sans-serif;
  font-weight: 500;
  font-size: 16px;
  letter-spacing: 1px;
  display: inline-block;
  padding: 10px 30px;
  border-radius: 50px;
  transition: 0.5s;
  color: #3498db !important; 
  border: 2px solid #3498db !important;
  }
  .btn:hover{
      background-color: black;
      color: white!important;
  }
</style>
{% endblock style %}

{% block content %}
<br><br><br><br><br><br><br><br><br><br>
<form class="" enctype="multipart/form-data" novalidate method="post" action="{% url 'Tricycleapp:confirmation' %}" >
  {% csrf_token %}
  <div class="row justify-content-center">
    <div class="col-md-5 col-lg-4 order-md-last mx-auto">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-primary"><h1 class="fs-3 fw-bolder">Récapitulatif</h1></span>
        <hr>
        <span class="badge bg-primary rounded-pill">1</span>
      </h4>
      <ul class="list-group mb-3">
        <li class="list-group-item d-flex justify-content-between lh-sm">
          <div>
            <h6 class="my-0" name="modele">{{ reservation.modele }}</h6>
            <small class="text-muted" name="name">{{ reservation.name }}</small>
          </div>
          <img src="{{ tricycle.image.url }}" alt="" style="max-width: 300px; max-height: 200px;">
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Nous allons vous défalquer </span>
          <strong name="price" value="{{ reservation.apayer }}">FCFA {{ reservation.apayer }}</strong>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Vous rester devoir </span>
          <strong name="price" value="{{ reservation.montant_restant }}">FCFA {{ reservation.montant_restant }}</strong>
        </li>
      </ul>
      <input type="hidden" name="reservation_id" value="{{ reservation.id }}">

      <div class="text-center">
        <button name="payer" class="btn" type="submit"> Payer</button>
      </div>
    </div>

  </div>
</form>


{% endblock content %}

templates/Tricycle/update.html
{% extends 'base.html' %}

{% block title %}Tricycle Modifier{% endblock %}

{% block content %}
	<h1 class="fs-3 fw-bolder text-center">Modifier les informations</h1>
	<div class="offset-3">
		<form method="post" class="row col-md-6 px-3" enctype="multipart/form-data">
			{% csrf_token %}
			{% for field in form %}
			<div class="mb-3">
				<label class="form-label">{{ field.label }}</label>
				{{ field }}
			</div>
			{% endfor %}
			<input type="submit" class="btn btn-primary" value="Modifier Voiture">
		</form>
	</div>
{% endblock content %}