Modele/urls.py
from django.urls import path
from . import views


app_name = 'Modele'


urlpatterns = [
	# post views
	path('<int:pk>/', views.ModeleDetail.as_view(), name='detail'),
	path('', views.ModeleListView.as_view(), name='list'),
	path('add/', views.ModeleCreateView.as_view(), name='add'),
	path('update/<int:pk>/', views.ModeleUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/', views.ModeleDeleteView.as_view(), name="delete")
]

Tricycle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
from django.conf.urls.i18n import i18n_patterns

from Tricycleapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.TricycleView.as_view(), name='index'),
    path('Tricycle',include('Tricycleapp.urls')),
    path('Tricycleauth/',include('Tricycleauth.urls')),
    path('Modele/', include('Modele.urls', namespace='Modele')),
    path('reservation/', views.ReservationView.as_view(), name='reservation'),
]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', views.TricycleView.as_view(), name='index'),
    path('Tricycle/',include('Tricycleapp.urls',namespace='tricycle')),
    path('Tricycleauth/',include('Tricycleauth.urls',namespace='tricycleauth')), 
    path('Modele/', include('Modele.urls', namespace='modele')),
    path('reservation/', views.ReservationView.as_view(), name='reservation'),
)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



'''
On utilise souvent un nom pour les apps quand on écrit plusieurs applications
et dont les noms des urls spnt les memes. Alors les app_namme permettent de se
rediriger vers cet url selin de nom de l'app defini
'''

Tricycleapp/urls.py
from django.urls import path
from Tricycleapp import views


app_name = 'Tricycleapp'

urlpatterns = [
    path('<int:pk>/', views.TricycleDetail.as_view(), name='detail'),
	path('list/', views.TricycleList.as_view(), name='list'),
	path('add/', views.TricycleAdd.as_view(), name='add'),
	path('update/<int:pk>/', views.TricycleUpdate.as_view(), name='update'),
	path('delete/<int:pk>/', views.TricycleDelete.as_view(), name="delete"),
	path('<int:pk>/achat/', views.TricycleAchat.as_view(), name='payement'),
	path('reservation/', views.ReservationView.as_view(), name='reservation'),
	path('confirmation/', views.payement_view, name='confirmation'),
	path('contact/',views.contact,name='contact')
  
]

Tricycleauth/urls.py
from django.urls import path
from Tricycleauth import views
app_name = 'Tricycleauth'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.handlelogin, name='handlelogin'),
    path('logout/',views.handlelogout,name='handlelogout'),
    path('activate/<uidb64>/<token>/',views.ActivateAccountView.as_view(),name='activate'),
    path('request-reset-email/', views.RequestResetEmailView.as_view(),name='request-reset-email'),
    path('set-new-password/<uidb64>/<token>/', views.SetNewPasswordView.as_view(),name='set-new-password'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
      
    <title>Kloboto | {% block title %}{% endblock %}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
      
    <!-- Favicons -->
    <link href=" {% static 'assets/img/favicon.jpg' %}" rel="icon">
    <link href=" {% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
      
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
      
    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
        
    <!-- owl carousels-->
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
        
    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    {% block style %}{% endblock style %}

    <!-- =======================================================
    * Template Name: Vesperr
    * Updated: Sep 18 2023 with Bootstrap v5.3.2
    * Template URL: https://bootstrapmade.com/vesperr-free-bootstrap-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>
<body>
	{% include 'header.html' %}

	<section>{% block content %} {% endblock content %}</section>

	{% include 'footer.html' %}
    {% block script %}{% endblock script %}
</body>
</html>

templates/footer.html
{% load static %}

<!-- ======= Footer ======= -->
<footer id="footer">
    <div class="container">
      <div class="row justify-content-center d-flex align-items-center">
        <div class="col-lg-6 text-lg-left text-center">
          <div class="copyright"> 
            &copy; Copyright <strong>10-20 TECHNOLOGIES</strong>. Tous droits réservés
          </div>
          <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/vesperr-free-bootstrap-template/ -->
          </div>
        </div>
        
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

  <!-- owl carousel script-->
  
  <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>

 

templates/header.html
{% load static %}
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <!-- Uncomment below if you prefer to use an image logo -->
        <a href="{% url 'index' %}"><img src="{% static 'assets/img/space/logo.jpg' %}" alt="" class="img-fluid" style="max-height: 100px;" ></a>
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          {% if request.resolver_match.view_name == 'index' %}
          <li><a class="nav-link scrollto active" href="{% url 'index' %}">Accueil</a></li> {% else %}
          <li><a class="nav-link scrollto active" href="{% url 'index' %}">Accueil</a></li>{% endif %}
          <li class="dropdown">
            <a href="{% url 'Modele:list' %}">
                <span>Modèles</span> <i class="bi bi-chevron-down"></i>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for modele in modeles %}
                    <li>
                        <a href="{% url 'Modele:detail' modele.pk %}">
                            <h5 class="card-title text-center">{{ modele.name }}</h5>
                        </a>
                    </li>
                {% endfor %}
            </ul>
          </li>
        
          <li>
            
            {% if request.resolver_match.view_name == 'tricycle:list' %}
              <a class="nav-link scrollto" href="{% url 'Tricycleapp:list' %}">Tricycles</a> 
            {% else %}
              <a class="nav-link" href="{% url 'Tricycleapp:list' %}">Tricycles</a> 
            {% endif %}
          </li>
          
          <li><a class="nav-link scrollto" href="{% url 'Tricycleauth:handlelogout' %}">Se déconnecter</a></li>
    {% if user.is_authenticated %}
          <li><a class="getstarted scrollto" href="#about">Bienvenu {{ user.last_name }}</a></li>
        {% else %}
        <li><a class="nav-link scrollto" href="{% url 'Tricycleauth:handlelogin' %}">Se connecter</a></li>
        </ul>
    {% endif%}
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->